[package]
name = "mastermind-rust"
version = "0.1.0"
authors = ["dmitry.travyan <dtrser@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.2"
ansi_term = "0.12.1"
